modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Desert-Temples/issues"

[[mods]]
	modId="betterdeserttemples"
	version="${file.jarVersion}"
	displayName="YUNG's Better Desert Temples"
	credits="Thanks so much to all my patrons!"
	authors="YUNGNICKYOUNG, Tera"
	description="A complete redesign of Minecraft's desert temples"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples"

[[dependencies.betterdeserttemples]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.betterdeserttemples]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"

[[dependencies.betterdeserttemples]]
    modId="yungsapi"
    versionRange="[1.19.2-Forge-3.5.0,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"